### PR TITLE
feat: build arm64 docker image of coinjoin-backend

### PR DESCRIPTION
**Pull request by vdovhanych**

### CODE REVIEW

**Comment by szymonlesisz** [comment]
cool 👍

**Comment by vdovhanych** [comment]
Todo - download middleware from https://github.com/trezor/WalletWasabi/releases. Is it okay that the container's default middleware will not be in debug mode? You could download debug the way you proposed with local file yes?

**Comment by szymonlesisz** [comment]
i would prefer to always have a debug build here (with swagger)

**Comment by vdovhanych** [comment]
> i would prefer to always have a debug build here (with swagger)

That would mean we would also need to release those builds somewhere. Not possible to download it from new artifacts as there is nothing like latest workflow artifact

**Pull request merged**
